name = "RFfusion"
uuid = "d8c5797e-6087-43ef-baa8-275c990658a0"
version = "0.1.0"
authors = ["Human Prime Generator"]

[deps]
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
Octonions = "d00ba074-1e29-4f5e-9fd4-d67071d6a14d"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.12"
Manifolds = "0.10.12"
